cp /net/s100dserv/xorApps/epics/mdw_ui/screens/autogenerated/crls/crl_*.ui .
cp /net/s100dserv/xorApps/epics/mdw_ui/screens/autogenerated/crls/lenses_*.ui .
cp /net/s100dserv/xorApps/epics/mdw_ui/screens/autogenerated/crls/stacks_*.ui .
