# This is a TOML document

title = "9ID CRL setup"

# Set up beam properties -- these may only need to be set up at creation of IOC
# however energy can be changed after boot-time and mode can be switched based
# on run-cycle?
# energy	 - energy in keV 
# L_und      - Undulator length in m
# Beam modes (flat/low-coupling, round/full-coupling) -- more info
# here: https://ops.aps.anl.gov/SRparameters/SRparameters.html
# sigmaH_e   - Sigma electron source size in H direction in m
# sigmaV_e   - Sigma electron source size in V direction in m
# sigmaHp_e  - Sigma electron divergence in H direction in rad
# sigmaVp_e  - Sigma electron divergence in V direction in rad
[beam]
energy = 15
L_und = 2.4
sigmaH_e.round = 12.296e-6
sigmaV_e.round = 8.263e-6
sigmaHp_e.round = 2.336e-6
sigmaVp_e.round = 3.474e-6
sigmaH_e.flat = 14.466e-6
sigmaV_e.flat = 3.075e-6
sigmaHp_e.flat = 2.749e-6
sigmaVp_e.flat = 1.293e-6

# Set up beamline properties -- these may only need to be set up at creation of IOC
# d_StoL1	- Source-to-CRL1 distance, in m
# d_StoL2	- Source-to-CRL2 distance, in m
# d_Stof	- Source-to-sample distance, in m
# f in I-station; for E-station: 56.3 m
[beamline]
d_StoL1 = 51.9
d_StoL2 = 62.1
d_Stof = 66.2


# Set up crl properties -- these are properties common to the stacks
# stacks	- Number of sets of lenses
# d_min 	- Minimum thickness at the apex in m
[crl1]
stacks = 10
d_min = 0.00003 

[crl2]
stacks = 10
d_min = 0.00003 


