# This is a TOML document

title = "CRL generic multi-system setup"

# Set up beam properties -- these may only need to be set up at creation of IOC
# however energy can be changed after boot-time and mode can be switched based
# on run-cycle?
# energy	 - energy in keV 
# L_und      - Undulator length in m
# Beam modes (flat/low-coupling, round/full-coupling) -- more info
# here: https://ops.aps.anl.gov/SRparameters/SRparameters.html
# sigmaH_e   - Sigma electron source size in H direction in m
# sigmaV_e   - Sigma electron source size in V direction in m
# sigmaHp_e  - Sigma electron divergence in H direction in rad
# sigmaVp_e  - Sigma electron divergence in V direction in rad
[beam]
energy = 15
L_und = 2.4
sigmaH_e.round = 12.296e-6
sigmaV_e.round = 8.263e-6
sigmaHp_e.round = 2.336e-6
sigmaVp_e.round = 3.474e-6
sigmaH_e.flat = 14.466e-6
sigmaV_e.flat = 3.075e-6
sigmaHp_e.flat = 2.749e-6
sigmaVp_e.flat = 1.293e-6

# Set up beamline properties -- these may only need to be set up at creation of IOC
# d_StoL	- Source-to-CRL distances, in m
# 			  includes flange-to-fiducial distance (240.1 mm, 239.7 mm)
# d_Stof	- Source-to-sample distance, in m
[beamline]
d_StoL = [52.140, 62.340]
d_Stof = [55.0, 66.2]


# Set up crl properties -- these are properties common to the stacks
# label		- Label/location of CRL (typically the hutch letter); needs to match subs file
# stacks	- Number of sets of lenses
# d_min 	- Minimum thickness at the apex in m
[crl1]
label = 'B'
stacks = 10
d_min = 0.00003 


[crl2]
label = 'C'
stacks = 10
d_min = 0.00003 

# KB input block
# KBH_L		-	KBH length
# KBH_q		-	KBH q
# KB_theta 	-	KB mirror angle
# KBV_L		-	KBV length
# KBV_q		-	KBV q
# KBH_p_limit - Minimum p that KBH can achieve, so abs(KBH_p) > KBH_p_min
# KBV_p_limit - Minimum p that KBV can achieve, so abs(KBV_p) > KBV_p_min
[kb]
KBH_L       = 180.0e-3          
KBH_q       = 380.0e-3          
KB_theta    = 2.5e-3            
KBV_L       = 300.0e-3          
KBV_q       = 640.0e-3          
KBH_p_limit = 1.0               
KBV_p_limit = 1.0       

# Initial setup block
# sysType - 1: single, 2: double, 3: single + KB
# elems - which CRLS to use in system at start; first element by default
#
# To start with double by default: sysType = 2, elems = [0,1] 
[init]
sysType = 1
elems = [0]
